name = "formal"
version = "2.0.0"
description = "Type safe HTML form decoding and validation!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "formal" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
